# Generated by Django 4.0.3 on 2022-10-02 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mou',
            old_name='file',
            new_name='mou',
        ),
    ]
