# Generated by Django 4.0.3 on 2022-10-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_placementreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('broucher', models.FileField(upload_to='Mou')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
