# Generated by Django 4.0.3 on 2022-10-02 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0004_broucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broucher',
            name='broucher',
            field=models.FileField(upload_to='broucher'),
        ),
        migrations.AlterField(
            model_name='placementreport',
            name='report',
            field=models.FileField(upload_to='Placementreport'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('passing_year', models.IntegerField()),
                ('branch', models.CharField(max_length=50)),
                ('cgpa', models.FloatField()),
                ('prn', models.CharField(max_length=8)),
                ('resume', models.FileField(upload_to='Resume')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
